version: '3.7'

services:
    balancer:
        image: nginx
        container_name: nginx
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 8080:80

    hello:
        image: nginx
        container_name: hello
        volumes:
            - ./destination.nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 3000:80
